### ISSUE TITLE
Add option to disable double-quotes around key names 

### ISSUE THREAD

**Issue by danr** [lydell/json-stringify-pretty-compact#13]
It would be nice - for debugging purposes - to view an object like this:
```javascript
{"ok": true, "example": {"a": 42, "b": 43}}
```
like this:
```javascript
{ok: true, example: {a: 42, b: 43}}
```
Thanks!

**Comment by lydell** [comment]
Thanks for the suggestion! However, this module deals with standard JSON only. You might be interested in [util.inspect](https://nodejs.org/api/util.html#util_util_inspect_object_options), though!

**Comment by danr** [comment]
Excellent! Thanks @lydell
