### ISSUE TITLE
Margins feature request.

### ISSUE THREAD

**Issue by T1MOXA** [lydell/json-stringify-pretty-compact#17]
There is a proposal to make an option that sets margins only for objects in which there is data.

For example:
```
{
	"data": {
		"object": {  },
		"array": [  ],
		"obj": { "bool": true }
	}
}
```
Become:
```
{
	"data": {
		"object": {},
		"array": [],
		"obj": { "bool": true }
	}
}
```

**Comment by lydell** [comment]
I thought it worked this way already. I wouldn't mind this being the one and only behavior (no new option). What do you think, @randallsquared? PRs welcome.

**Comment by domoritz** [comment]
I prefer the current behavior because it makes the empty objects more visible and easier to put the cursor between the curly braces. It's also more consistent.

**Comment by lydell** [comment]
Hmm, I'm starting to feel I should never have merged that PR … we've opened a can of worms.

**Comment by lydell** [comment]
Sounds too complicated to me.

**Comment by randallsquared** [comment]
I thought you might say that. :)

Adding another option entirely seems like too much.

The `margins` option could take some other, simpler thing that allows empties to be collapsed, like`'non-empty'`, in addition to `true` and `false`.  Given that the docs currently require a boolean, I've changed my mind about whether such an addition would required a version change.

**Comment by domoritz** [comment]
Another option is to have simple behavior where empty objects are `{}` when margins are disabled and `{  }` when margins are on. If you don't like the behavior, you can run a simple search and replace `stringify(object).replace('{}', '{ }')` (this only breaks in comments but that seems acceptable). What do you think?

**Comment by randallsquared** [comment]
>  empty objects are `{}` when margins are disabled and `{  }` when margins are on.

Isn't that what happens now, @domoritz ?

**Comment by domoritz** [comment]
Yes, that's the point 😀.

**Comment by lydell** [comment]
`margins` has been removed in 2.0.0. Use [@aitodotai/json-stringify-pretty-compact](https://www.npmjs.com/package/@aitodotai/json-stringify-pretty-compact) if you want it back.
