### ISSUE TITLE
npmjs package page doesn't show readme

### ISSUE THREAD

**Issue by josephfrazier** [lydell/json-stringify-pretty-compact#3]
At https://www.npmjs.com/package/json-stringify-pretty-compact, it says there is no readme. This is because the published package does not include README.md:

```bash
$ tar tvf $(npm pack json-stringify-pretty-compact)
-rw-rw-r--  0 1000   1000      698 Sep  8  2016 package/package.json
-rw-rw-r--  0 1000   1000     1085 Sep  8  2016 package/LICENSE
-rw-rw-r--  0 1000   1000     2490 Sep  8  2016 package/index.js
-rw-rw-r--  0 1000   1000      341 Sep  8  2016 package/CHANGELOG.md
```

According to https://github.com/npm/registry/issues/120#issuecomment-276157329, old versions of npm didn't include README.md. If you upgrade your npm version, and publish a patch release of this module, the readme should appear on npmjs.com.

---

(issue markdown adapted from https://github.com/domenic/opener/issues/24)

**Comment by lydell** [comment]
Thanks! It should be up now.

**Comment by lydell** [comment]
Thanks! It should be up now.

**Comment by duzun** [comment]
What was the issue?
Same issue with [url-js](https://www.npmjs.com/package/url-js) after an update :-(
Is it up to me (owner) to fix it?
