### ISSUE TITLE
Online convertor

### ISSUE THREAD

**Issue by soxofaan** [lydell/json-stringify-pretty-compact#42]
Is there an online version of this tool?
E.g. a simple page hosted through github pages?

**Comment by soxofaan** [comment]
For my own needs I already created this extremely rudimentary single-file/vanilla-JS/vanilla-CSS index.html: https://github.com/soxofaan/json-stringify-pretty-compact/blob/issue42-online-demo/index.html 
It's functional through github pages at https://soxofaan.github.io/json-stringify-pretty-compact/

My frontend/javascript skills are a quite rusty, but if this could be a starting point for a prettier online json-stringify-pretty-compact convertor, I'll create a PR from this

**Comment by lydell** [comment]
Good idea! Thank you for that simple demo you made, it inspired me to make something similar:

https://lydell.github.io/json-stringify-pretty-compact/

I didn’t include the stats from your demo (chars, lines, longest line) – let me know if you have a use case for those.
