### ISSUE TITLE
thanks

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [lydell/json-stringify-pretty-compact#44]
Hi

Just wanted to say thank you. I added your code to https://arkenfox.github.io/TZP/tzp.html, tweaked it a little to suit and added colors (to match Firefox dark theme dev console - it really makes some of the data so much more compact when testing/inspecting

all the clickable details/metrics etc popup an overlay which I populate with the relevant JSON

since it only runs on gecko browsers (Firefox 102 based or higher), here's a pic. I've credited and linked to this repo at the top, in the pic you can just see `lydell` on the top right under the overlay

![thanks](https://github.com/lydell/json-stringify-pretty-compact/assets/16656956/e754a7a6-801f-4f18-a95d-5654f683605c)

**Comment by lydell** [comment]
Hi! Glad you like, and thanks for letting me know! 💙
