### ISSUE TITLE
Support a way to adjust the algorithm based on the object

### ISSUE THREAD

**Issue by powellquiring** [lydell/json-stringify-pretty-compact#5]
I want some objects to be on a single line regardless of their length.

This is so I can more easily deal with the json file in an editor (search for multiple keys and values with regular expressions and make editing changes)

This is what I was thinking for the implementation

Pass a callback function that would take as a parameter the current object being stringify'ed would work in my case:  function(obj)

There is a more complicated call back mechanism defined here: https://www.npmjs.com/package/pretty-json-stringify  This is more then I need, but might add some generality.  function(object, level, key)  

It isn't clear to me what context would be generally useful for the callback.  I think an array representing the path to the object's parent would be helpful

{ a: {b: {c: {d: [ "e", {f: "g"}]}}})

So when callback({f: "g"}) is being handled the parent would be:
["a", "b", "c", "d", 1]

**Comment by powellquiring** [comment]
https://github.com/lydell/json-stringify-pretty-compact/pull/6 

After looking more closely at the algorithm, my suggested strategy works better when the maxLength values are small forcing the callout to be called for each object.  The suggestion of passing the parent wouldn't work since not all children are visited.

**Comment by lydell** [comment]
Hi! I'm glad to hear that you find json-stringify-pretty-compact useful. This sounds like a very niche use case, though. json-stringify-pretty-compact is not very complicated and not likely to change much, so I suggest you simply fork it and add whatever features you need. If you end up with something you like, please share it here and I'll add a link to it so other people can find it too!
